Laget enumerator for parameteret "approve".
statisticsnorway/dapla-statbank-client pull request #103
Opened 2024-03-05 14:31 UTC by Bjoern-Rapp

Dette gir bedre typehint.
Brukere vil nå kunne sende inn 0, 1 og 2 som før, eller Approve.MANUAL,  Approve.AUTOMATIC eller Approve..JIT.

2024-03-08 11:21 UTC, aecorn requested changes
Kommer til å godta denne PRen, om du skriver en test som beviser at `search__dict__()` fortsatt finner ting dypt inne i attributtene på objekter.

Akkurat nå beviser vi kun ett "negativt case" hvor "om search__dict__ funker OG ting IKKE er i objektet" så kjører ting ok.
Jeg er ute etter ett case som beviser at `search__dict__` funker alene.

2024-03-08 11:29 UTC, Bjoern-Rapp commented
Det kan jeg gjøre, selvsagt gjøre. Men merk at ikke alle klasser lagrer attributtene sine i et dict. Python har også klasser som lagrer attributtene sine i slots.
https://www.pythontutorial.net/python-oop/python-__slots__/

2024-03-08 11:59 UTC, aecorn commented
> Det kan jeg selvsagt gjøre. Men merk at ikke alle klasser lagrer attributtene sine i et dict. Python har også klasser som lagrer attributtene sine i slots. https://www.pythontutorial.net/python-oop/python-__slots__/

Yes, det viktigste denne gjør er å lete gjennom objekter som kommer tilbake fra requestbiblioteket. Og forsikre oss om at det ikke ligger noen "rester av noe skummelt" i de, siden resten er en god "logg" over hva som har kommet tilbake ved overføringer.

Dvs. vi vil rense ut alle muligheter for at passord, brukernavn kan ligge i resultat-objektene, før vi evt. tar vare på dem som noe som kan inngå i logg/metadata. Om requestbiblioteket plutselig begynner å lagre slikt "andre steder i objektene" så vil jeg gjerne fange opp det. Om du tenker det er greit å lete gjennom slots også, så utvid gjerne search__dict__ til å gjøre det, evt. skriv en search__slots__ som vi kan kalle i tillegg. Men hittils har .__dict__ funnet det meste fra request-biblioteket som jeg har sett etter, så pass på at det ikke gjøres arbeid som du anseer som unødvendig.

2024-03-11 10:19 UTC, aecorn requested changes

2024-03-11 10:19 UTC, aecorn commented on tests/test_statbank.py
> +    # Make sure none of these are in the object for security
Change this comment to "make sure we now find the inserted auth, verifying that search__dict__ is doing its job". Or similar. Thanks!

2024-03-11 12:08 UTC, closed without merging